[tool.poetry]
name = "innohassle-accounts"
version = "0.1.0"
description = ""
authors = ["Ruslan Bel'kov <ruslan.belckov@yandex.ru>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
authlib = "^1.2.1"
beanie = "^1.27.0"
colorlog = "^6.9.0"
fastapi = "^0.115.4"
fastapi-swagger = "^0.2.3"
gunicorn = "23.0.0"
httpx = "^0.27.0"
itsdangerous = "^2.1.2"
pre-commit = "^4.0.1"
pydantic = {extras = ["email"], version = "^2.6.3"}
python-multipart = "^0.0.17"
pyyaml = "^6.0.1"
ruff = "^0.7.1"
uvicorn = "^0.32.0"

[tool.ruff]
line-length = 120
lint.ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
    "PLR"
]
lint.extend-select = ["I", "UP", "PL"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
